# 
# OVERVIEW
#
# This script uses xml files, generated by the profiling tool Valgrind memcheck,
# from a prefined directory and calls a python script `xml2junit_converter`. 
# The result is stored in a predefined output directory.
#
# USAGE 
# 
# The script can be used together with a custom_command or custom_target.
# See example below: 
# 
# COMMAND ${CMAKE_COMMAND} -Dinput_directory=${input_directory} 
#                          -Doutput_directory=${output_directory}
#                          -Djunit_options=${options} 
#                          -P <path_to_script>/JunitGenerator.cmake
#
# The parameters input_directory, output_directory, and junit_options needs to
# be defined.
#

file(GLOB_RECURSE filenames ${input_directory}/*xml*)
foreach(file_path ${filenames})
  execute_process(
    COMMAND python xml2junit_converter.py ${file_path} ${output_directory} ${junit_options}
    WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/python_scripts
  )
endforeach()
